name: CI

on:
  push:
    branches:
      - release
  pull_request:

jobs:
  build:
    name: Build scripts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Compile
        run: |
          BUILD=$(($(git rev-list --count --first-parent HEAD)+3500))
          TODAY=$(date +"%d.%m.%y")
          echo "BUILD=${BUILD}" >> "$GITHUB_ENV"
          echo "TODAY=${TODAY}" >> "$GITHUB_ENV"
          echo "Build number ${BUILD}"
          mkdir -p ciout
          LAST=$(<current/last)
          if [ "$LAST" == "" ]; then LAST=1; fi
          if [ -f current/last_idn ]; then LAST_IDN=$(<current/last_idn); else LAST_IDN="$LAST" ; fi
          php update-manager/update-manager.php dscript "ciout/idn.txt" . idn ${BUILD} || exit 1
          cp misc/game.hash ciout
          cp misc/default.cfg ciout
          cd ciout
          zip -qry umineko-idn-scripts_r${BUILD}_dev.zip idn.txt default.cfg game.hash || exit 1
          cd ..
          php update-manager/update-manager.php script ciout/idn.txt "ciout/idn.file" "$LAST_IDN" || exit 1
          cd ciout
          zip -qry umineko-idn-scripts_r${BUILD}.zip idn.file default.cfg game.hash || exit 1
          cd ..
          git show -s --format="%s" > release_notes.md
          echo "Refer to https://umineko-indo.vercel.app for more details." >> release_notes.md

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ env.BUILD }}
          release_name: Release v${{ env.BUILD }}
          body_path: release_notes.md
          draft: false
          prerelease: false
    
      - name: Upload IDN
        if: github.repository_owner == 'andikaalakate' && github.ref_name == 'release'
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./ciout/umineko-idn-scripts_r${{ env.BUILD }}.zip
          asset_name: umineko-idn-scripts_r${{ env.BUILD }}.zip
          asset_content_type: application/zip

      - name: Upload IDN (dev)
        if: github.repository_owner == 'andikaalakate' && github.ref_name == 'release'
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./ciout/umineko-idn-scripts_r${{ env.BUILD }}_dev.zip
          asset_name: umineko-idn-scripts_r${{ env.BUILD }}_dev.zip
          asset_content_type: application/zip
